### PR TITLE
fix: remove conda-forge channel

### PR DESCRIPTION
**Pull request by redeboer**
See https://github.com/ComPWA/tensorwaves/pull/133

### CODE REVIEW

**Comment by spflueger** [comment]
So something was missing in the previous PR?

**Comment by redeboer** [comment]
> So something was missing in the previous PR?

Wow this is weird yes. Sorrry I messed up something extracting this commit from #324

**Review by spflueger — APPROVED** [review]

**Comment by redeboer** [comment]
@spflueger Now I think it may make sense to make one job that checks the Conda developer setup. This problem arose because 
 conda-forge made 3.9 available and I only noticed when I recreated my environment. There may be other smaller issues when running conda, so might be a good idea to have that tested.

I'll push a try-out commit, then you can judge.

**Comment by spflueger** [comment]
Sounds good

**Comment by redeboer** [comment]
Hmm, I give up. To get it working you have to apply so many tricks that I doubt whether it's still a proper 'test'. So I'll leave it with the bug fix (will merge once CI is done)

**Pull request merged**
