### PR TITLE
ci: update requirements through GitHub Actions

### LINKED ISSUE #409: Pin all nested dependencies for different Python versions
_This issue serves as a summary of the findings for #402_

Since #102, we list all dependencies in the [`setup.cfg`](https://github.com/ComPWA/expertsystem/blob/7daef69533b19e7c57122bb23fe44bedfe429bc2/setup.cfg) file. We make a distinction between package requirements (defined by `install_requires`) and additional dependencies (defined through different sections like `doc` and `sty` under `extras_require`).

Each of the versions of dependencies were pinned in the `setup.cfg` file, so that developers use the same version. However, this does not pin _indirect_ dependencies, like `pyrsistent` (which is required by `jsonschema`)

Since #394, we therefore pin _both direct and indirect_ dependencies through `requirements.txt` and `requirements-dev.txt`. These files are created with `pip-compile` ([`pip-tools`](https://github.com/jazzband/pip-tools)) in a `tox` job (`tox -e upgrade`). Input files are **unpinned** dependency files (in **bold** the files that are relevant for the user/developer):

| Unpinned        | Pinned output              |
| :-------------- | :------------------------- |
| **`setup.cfg`** | **`requirements.txt`**     |
| `.reqs/doc.in`  | `.reqs/doc.txt`            |
| `.reqs/sty.in`  | `.reqs/sty.txt`            |
| `.reqs/test.in` | `.reqs/test.txt`           |
| `.reqs/dev.in`  | **`requirements-dev.txt`** |

There is a certain hierarchy in these files: for instance, `requirements-dev.txt` contains all dependencies that are listed in `requirements.txt`. This dependency is defined in the `tox -e upgrade` job.

There are some problems/challenges with this setup though:

1. Requirements differ per Python version. For instance, some package work with `importlib-resources` for Python <= 3.7. There should therefore be versions for each of the files in the right column _for each version of Python_.

   > **Proposed solution**
   >
   > Follow a new folder structure: remove the `.reqs` folder in favour of a `dev` folder that contains the [`.in` files](https://github.com/jazzband/pip-tools#example-usage-for-pip-compile). These files list _unpinned_ dependencies (at most a certain version range). This `dev` folder has subfolders `dev/3.6`, `dev/3.7`, and `dev/3.8` that contain _pinned_ requirement files. These files are created with `pip-compile` from the `.in` files.

2. Ideally, we want these pinned requirement files to be compatible, so that you can for instance do

   ```bash
   pip install -r requirements.txt -r requirements-dev.txt
   ```

   In other words, there should be no version conflicts between duplicate dependencies listed in each of the files.

   > **Proposed solution**
   >
   > Run a specific sequence of `pip-compile` commands through a GitHub Action (see `ci-dev.yml`). This allows us to created pinned `.txt` files first, then use those as constraint files (`-c`) in the `.in` files. So there will be two types of `.in` files: the ones that only list the dependencies themselves (for instance `*-sty.in`) and the ones that the ones that use those `.in` files along with constraints/requirements (`-c`/`-r`), say, `*-sty-deps.in`.
   >
   > Splitting the `.in` files into 'bare' requirement listings and dependency listings between the `.in` files is required for 'forward constraining', that is ensuring that `pip-compile` takes into account that, say, `requirements-sty.in` will introduce a version of `importlib-metadata` that is limited to a certain max, while the (prior) `requirements-test.in` will pin `importlib-metadata` to the latest release. This would cause conflicts when creating `requirements-dev.txt`, which should contain both `requirements-test.txt` and `requirements-sty.txt`.
   >
   > **One problem here: `pip-compile` does not support constraint flags, so we have to feed these through the `*.in` files. This also means we need a `requirements.in` files that lists exactly the same as the `setup.cfg` file.**

3. All `requirement*.txt` files need to be upgraded once one of the dependencies changes. Dependency changes only take place in `setup.cfg` and the `*.in` files.

   > **Proposed solution**
   >
   > The `requirements*.txt` files should be updated automatically, so this has to be done through a GitHub Action _upon every PR_. GitHub Actions cannot push to branches that are on a fork, so this means a separate PR should be spawned _if_ there changed in the `setup.cfg` or `.in` files are detected.

4. How to handle updates in the dependencies?

   > In order to keep the pinned `requirements*.txt` files up-to-date, a cron job should _upgrade_ these files. This is the same as 3., but using `pip-compile` with the flag `--upgrade`.

### PR DESCRIPTION
**Pull request by redeboer**
Closes #409 
Closes #402

Requirements differ for each version of Python. We therefore have to maintain `requirement.txt` files for each version of Python that we supports. It is, however, hard to update these lists manually, so it is better to do this through a GitHub workflow (which has access to all versions of Python).

See also
https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile 

- [x] Write `requirements.txt` files to different subfolders `dev/3.6`, `dev/3.7`, `dev/3.8` in GitHub Actions
- [x] Fix dependency conflicts `importlib-resources` and `importlib-metadata` for Python 3.6-3.7
- [x] Run only on changes to `setup.cfg` and `*.in` files (`git diff` non-empty) --> abac046 and f17f0d8
- [x] Revert to using `skip-install` and [`whitelist_externals`](https://tox.readthedocs.io/en/latest/config.html?highlight=whitelist_externals#conf-allowlist_externals) in `tox` --> 8c2c1e0
- [x] Pin Python version in Conda `environment.yml` file --> 7f2a06c
- [x] Re-introduce `tox -e upgrade` --> 0600b01
- [x] Commit and push changes to PR through GitHub Actions upon changes to requirements --> https://github.com/ComPWA/expertsystem/pull/402#issuecomment-746171501
- [x] Run cron job for master branch --> 0c605ee
- [x] Test in a temporary repository --> https://github.com/ComPWA/expertsystem/pull/402#issuecomment-746171501
  - [x] Test pushing upon changes to `setup.cfg` and `reqs`
    <details>
    <summary>✅ Works</summary>
    redeboer/expertsystem-test-cron-job/pull/2
    
    </details>
  - [x] Test PR creation through cron job upon updates
    <details>
    <summary>✅ Works</summary>
    redeboer/expertsystem-test-cron-job/pull/5<br>
    <a href=https://github.com/redeboer/expertsystem-test-cron-job/actions/runs/426375571>https://github.com/redeboer/expertsystem-test-cron-job/actions/runs/426375571</a>
    
    </details>
  - [x] Test skipping PR creation through cron job when no updates
    <details>
    <summary>✅ Works</summary>
    <a href=https://github.com/redeboer/expertsystem-test-cron-job/runs/1565989056>https://github.com/redeboer/expertsystem-test-cron-job/runs/1565989056</a>
    
    </details>
  - [x] Test abort if no changes to `setup.cfg` or `reqs` --> dce0460
    <details>
    <summary>✅ Works</summary>
    redeboer/expertsystem-test-cron-job/pull/6<br>
    <a href=https://github.com/redeboer/expertsystem-test-cron-job/pull/6/checks?check_run_id=1566702836>https://github.com/redeboer/expertsystem-test-cron-job/pull/6/checks?check_run_id=1566702836</a><br>
    
    </details>
  - [x] Test error if modifying dependencies through a fork PR --> dce0460
    <details>
    <summary>✅ Works</summary>
    redeboer/expertsystem-test-cron-job/pull/7<br>
    <a href=https://github.com/redeboer/expertsystem-test-cron-job/actions/runs/426703151>https://github.com/redeboer/expertsystem-test-cron-job/actions/runs/426703151</a><br>
    
    </details>

### CODE REVIEW

**Comment by redeboer** [comment]
Ok so... new problems...
1. `pip-compile` output fluctuates between `typing-extensions` and `typing_extensions`, see e.g. 2fbd5c9, 1a720cc, 8513a88
2. CI does not boot upon commits that are pushed through GitHub actions

**Comment by redeboer** [comment]
e92dd1a (PAT) doesn't work yet

**Comment by redeboer** [comment]
Ok seems that 7a6b611 does the job

**Review by spflueger — APPROVED** [review]
GJ

**Pull request merged**
