### PR TITLE
feat: ignore name and pid in Particle comparison

### LINKED ISSUE #293: Ignore name and pid in Particle comparison
The `name` and `pid` attributes of `Particle` should become mere labels so that only the quantum numbers and properties like mass and width make a `Particle` uniquely distinguishable. This also has consequences for the behaviour of `ParticleCollection`. For more info see the comments in PR #292.

### PR DESCRIPTION
**Pull request by redeboer**
Closes #293

### CODE REVIEW

**Comment by redeboer** [comment]
@spflueger This PR is currently rather trivial, because I thought it would be more complicated. But maybe I'm missing something. For instance, how should the `__hash__` method of a `Particle` behave now?

**Review by spflueger — APPROVED** [review]

**Comment by spflueger** [comment]
> @spflueger This PR is currently rather trivial, because I thought it would be more complicated. But maybe I'm missing something. For instance, how should the `__hash__` method of a `Particle` behave now?

Things should work as expected (see note). You can add a test for checking the hash is the same for the two particles with different name or pid

```python3
assert hash(particle) == hash(different_name_particle)
```

Note: Afaik the dataclasses module will create a `__hash__` method now (since particle if frozen and comparable). As the name and pid are stated as non comparable fields, these values should neither be in the `__hash__` implementation nor the `__eq__` (generated by dataclasses).

**Comment by redeboer** [comment]
> Afaik the dataclasses module will create a __hash__ method now (since particle if frozen and comparable).

Yes, so actually this needs to be fixed still (and indeed tested), because the `__hash__` method is currently overwritten.

**Review by spflueger — CHANGES_REQUESTED** [review]
Ah I missed that. The `__hash__` function should be removed

**Comment by redeboer** [comment]
> Ah I missed that. The __hash__ function should be removed

Ok done now. There are still some things to be fixed now in the `ParticleCollection` but better to address that in #292

**Review by spflueger — APPROVED** [review]

**Pull request merged**
